### ISSUE TITLE
Splitting project for go get usage

### ISSUE THREAD

**Issue by nikolauska** [DeKugelschieber/asl#15]
It would be good to split project into individual parts that you can use go get command to fetch code and make it possible to have multiple go projects in same place.

This would of course require to create organization for this project
Example usage:

```
go get github.com/arma-scripting-language/tokenizer
go get github.com/arma-scripting-language/parser
go get github.com/arma-scripting-language/asl
```

**Comment by Kugelschieber** [comment]
I'll do that. The tokenizer is stateless and the parser has its own context now.
Maybe I will implement the preprocessor first.

**Comment by Kugelschieber** [comment]
Done.

**Comment by nikolauska** [comment]
Well you didn't really add this functionality. Current way still includes whole source folder, which it shouldn't do. 

Every src folder should be in it's own repository like in example where I used arma-scripting-language as a name for organization. This is how many open source go projects have set up their codebase. One organization, multiple smaller repos which contain small part. 

That way I could for example make small side project using only tokenizer and I could easily do

```
go get github.com/arma-scripting-language/tokenizer
```

and then in import 

```
import "github.com/arma-scripting-language/tokenizer"
```

Now I would be able to use tokenizer without manually copying folders to different path.

**Comment by Kugelschieber** [comment]
Ah ok, I misunderstood that. I'll see what I can do.

**Comment by nikolauska** [comment]
I can also do this if you want. I can transfer organization ownership to you after it has been set up

**Comment by Kugelschieber** [comment]
Okay, you can try it if you like.

**Comment by nikolauska** [comment]
It has now been created https://github.com/arma-scripting-language.

I had to make small code edits to make it work, like imports now uses github address and test folder is now on both parser and tokenizer.

**Comment by Kugelschieber** [comment]
I'll have to try that out, couldn't it be some kind of annoying to manage multiple repos for one program?
I thought go get works on submodules. So an git init in the packages should have been enough?

**Comment by nikolauska** [comment]
If there is only one developer, then yes it's little bit more work. But when there is more people working on project it will get lot easier to manage.

Other cool thing this allows is split asl to different modules like one for building scripts for mods and other for building scripts for mission. Having parser and token in different reposity allows this with using only imports. Having all in one project mean we have to copy both parser and tokenizer to another project and that would be hard to manage when either one is updated.

## Example

I have folder system that my mod uses, but currently asl doesn't allow me to build it like that so I need to make my own implementation.

### With split repositories:
- `go get github.com/arma-scripting-language/parser`
- `go get github.com/arma-scripting-language/tokenizer`
- Now just import them to project and start working

On update:
- `got get -u all`
- build project again

### With single repository:
- `git clone https://github.com/DeKugelschieber/asl.git`
- 1. Set GOPATH to this project and replace main with your own code
- 2. Copy tokenizer and parser to your GOPATH/src folder and import them

On update:
- 1. Git clone again and copy them to your project
- 2. Git clone and overwrite old code from GOPATH/src
- build project again

**Comment by Kugelschieber** [comment]
Alright, sounds great! :)
Can you add this to the README below contribute?

It would be also great to seperate tests, currently the test ASL files are redundant.

**Comment by nikolauska** [comment]
I think it would be best to add my text to CONTRIBUTING.md as github suggest to have documentation for contributors.

Maybe you should add me on skype (nikolauska1) so we don't need to communicate on issue comments :)

**Comment by Kugelschieber** [comment]
Well I've thought about it. Now I got three repos to manage and as it is, there is no good reason to split tokenizer, parser and main. I see this as one product and cannot imagen anyone using the tokenizer or the parser exclusivly.

Do you plan to use parts of it for yourself? Currently ASL is under heavy development for 1.1.0 and this three repo thing slows me down. I'm not quite satisfied with this solution...

There is maybe another solution for it, by managing submodules in one repo. I'll try that out.

**Comment by nikolauska** [comment]
Then would it be best to have all code in same main package. That way you don't have to have src folder in repository and everything is in same folder that could also be easily gotten with go get.

**Comment by Kugelschieber** [comment]
Ah right that should work.

**Comment by nikolauska** [comment]
I have done this to separate branch and at the same time I improved test by combining them. I will hopefully soon have pull request for you.
