### ISSUE TITLE
Files With the Same Name Aren't Compiled

### ISSUE THREAD

**Issue by 654wak654** [DeKugelschieber/asl#33]
If a file has the same name with a file in the most upper folder, it isn't compiled. The processes still creates an empty folder though.

Made some tests, imagine Input dir parameter is "D:\Folder". If the scripts are like the following:

```
"D:\Folder\test_script.asl"
"D:\Folder\new_folder\test_script.asl"
```

Only the script in the upper folder will be compiled, but en empty `new_folder` will still be created.  The following examples both work, so it has to do with the script in the first folder:

```
"D:\Folder\new_folder_0\test_script.asl"
"D:\Folder\new_folder_1\test_script.asl"
```

```
"D:\Folder\new_folder\test_script.asl"
"D:\Folder\new_folder\newer_folder\test_script.asl"
```

**Comment by Kugelschieber** [comment]
Seems to be an issue on windows only.
It works on Linux.

**Comment by 654wak654** [comment]
Will do a test on a different PC, see if it's on my end.

**Comment by 654wak654** [comment]
Issue only seems to occur on my PC, and only on the C drive. Every other Windows seems to be fine, tested with Windows 10 and Server 2012 R2.
