### ISSUE TITLE
Inline code

### ISSUE THREAD

**Issue by Kugelschieber** [DeKugelschieber/asl#6]
Inlining code is not possible, example:

```
_x addEventHandler ["CuratorGroupPlaced", {[_this, "ZeusGrpPlaced"] spawn BIS_fnc_MP}];
```

Need a solution for this.

**Comment by CaptainPStar** [comment]
Proposal: Create datatypes than can be parsed and are tested by the compiler:

_Code("[_this, /"ZeusGrpPlaced/"] spawn BIS_fnc_MP")_ will be translated to {[_this, "ZeusGrpPlaced"] spawn BIS_fnc_MP} in sqf.
Int(1) -> 1
Double(1) -> 1.0
 Tokenizing a Keyword (Code, Int, ...) sould be easier than parsing the plan inline code.

**Comment by Kugelschieber** [comment]
Strings are currently tokenized as one. So "[_this, /"ZeusGrpPlaced/"] spawn BIS_fnc_MP" will be one token, which should make it easy to parse it on its own and insert the result into brackets {}.
That could be a nice solution.
