### ISSUE TITLE
Feature request: function library compability

### ISSUE THREAD

**Issue by Kugelschieber** [DeKugelschieber/asl#7]
Looks nice and handy! Unfortunately I am using the function framework since A3 and it doesn't look like your compiler supports this at the moment. Maybe you should consider compiling your functions into fn_functionname.sqf files and automatically register them in description.ext or config.
This way you could even make c-like entry point functions (int main()) using preinit/postinit.
Do you plan to emulate classes in the future?

by NeoArmageddon
see: https://forums.bistudio.com/topic/185649-asl-arma-scripting-language-compiler/

**Comment by CaptainPStar** [comment]
See my comment at nikolauskas pull request.
